# Creative Keys mod metadata
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

# Issue tracker for user support
issueTrackerURL="https://github.com/TatosTV/creative-keys/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"

# Optional URLs for better user experience
displayURL="https://github.com/TatosTV/creative-keys"
credits="Built for content creators and server administrators"

# Dependencies with broader compatibility ranges
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)" # Accept any NeoForge version from current onwards
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}" # 1.21.1 to 1.22 (exclusive)
ordering="NONE"
side="BOTH"