name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases and upload assets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Find JAR file
        id: jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
          echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Creative Keys ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Creative Keys v${{ steps.version.outputs.VERSION }}
            
            A lightweight NeoForge mod that adds Creative Key items for server recordings and content creation.
            
            ### Installation
            1. Download the JAR file below
            2. Place it in your `mods/` folder
            3. Launch Minecraft with NeoForge 21.1.205+
            
            ### Requirements
            - Minecraft 1.21.1
            - NeoForge 21.1.205 or later
            - Java 21
            
            ### Changes
            See the commit history for detailed changes in this release.

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.jar.outputs.JAR_PATH }}
          asset_name: ${{ steps.jar.outputs.JAR_NAME }}
          asset_content_type: application/java-archive